### ISSUE TITLE
Loess normalization of balanced data

### ISSUE THREAD

**Issue by Phlya** [dozmorovlab/HiCcompare#10]
Hi. Do you think it's wrong to use balanced (iteratively corrected) data in loess normalization? Why I am asking, is currently HiCcompare doesn't detect some true differences in my datasets (i.e. "obvious" differences by eye, and validated biologically). Maybe there are some other ways to tweak the algorithm, but I can see that balancing the data improves fold change for some of them a lot... So is there a reason not to do this?

**Comment by jstansfield0** [comment]
I would recommend playing with the filtering before trying to use ICE'd data. You can use the `filter_params()` function to get a better idea of what level of filtering you should be using. 

As for using the ICE'd data, yes it will be accepted by the functions and should run fine. But you might be over normalizing the data.

**Comment by Phlya** [comment]
OK, thanks. Using `filter_params` is slightly challenging because I run everything on the cluster... Maybe I can save the object and then load it locally? I'll give it a go.

**Comment by jstansfield0** [comment]
Try saving the `hic.table` for a single chromosome as an object after you normalize it and then load it locally to use `filter_params`.
