### ISSUE TITLE
Note: wrong number of arguments to 'ceiling'

### ISSUE THREAD

**Issue by paulmenzel** [dozmorovlab/HiCcompare#11]
Building the package with R 3.6.0 gives the warning below.

```
* installing *source* package ‘HiCcompare’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Note: wrong number of arguments to 'ceiling'
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (HiCcompare)
```

**Comment by mdozmorov** [comment]
Thanks, @paulmenzel, for noticing. @jstansfield0, any thoughts? I can see the function appears in a few places, but don't see anything that may generate such warning. 
````
./R/hic_compare.R:99:    A.min <- mean(A_q10) %>% ceiling()
./R/hic_compare.R:183:  dist_85 <- ceiling(0.85 * length(all_dist))
./R/hic_diff.R:157:  dist_85 <- ceiling(0.85 * length(all_dist))
````
It doesn't seem the problem of R, Google gives the reference back to 2018, https://bioc.ism.ac.jp/checkResults/3.7/bioc-LATEST/HiCcompare/tokay2-install.html

**Comment by jstansfield0** [comment]
I'm not sure why you are getting that note. Does the package build and work for you when you try the examples or run the vignette? If so, I don't think there is actually any problem.

**Comment by mdozmorov** [comment]
Closed due to a non-critical warning. Reopen if it causes troubles.

**Comment by paulmenzel** [comment]
How should somebody know, if it causes trouble? The example I tested looked alright, but that does mean anything.

**Comment by mdozmorov** [comment]
We have tested the package extensively using the ground-truth data and getting the expected results, as described in the paper. We have not experienced any issues that may be caused by this warning.

**Comment by abbassix** [comment]
I suppose it is because of using pipeline operator.

**Comment by mdozmorov** [comment]
Thanks, @mehdi-abbassi, @jstansfield0, please, check when you get a chance.
