### ISSUE TITLE
Can it work for inter-chromosome differential interaction?

### ISSUE THREAD

**Issue by qianXX** [dozmorovlab/HiCcompare#13]
Hi!

I ues this software to find differential interactions.My input is HiC-Pro format. 

I can get results by following your document. But your document seem to work on single chromosome. Now I want to know, can it work for inter-chromosome differential interaction? 

Thanks!

**Comment by mdozmorov** [comment]
No, HiCcompare doesn't work on inter-chromosomal matrices. They are non-symmetric, so the concept of distance used for the joint normalization and differential analysis is much harder.
