### ISSUE TITLE
KRnorm

### ISSUE THREAD

**Issue by BenxiaHu** [dozmorovlab/HiCcompare#19]
Hi,
    I am trying to use HiCcompare to jointly normalize multiple Hi-C.  After running hic_loess, do I need to run KRnorm to normalize individual normalized matrix made by hic_loess?

**Comment by mdozmorov** [comment]
No. HiCcompare normalized both matrices to minimize differences between them. Note that HiCcompare normalizes two matrices, but KR is for individual matrices.
