### ISSUE TITLE
Inefficient matrix multiplication in KR norm

### ISSUE THREAD

**Issue by jnasser3** [dozmorovlab/HiCcompare#2]
Hello,

Thank you for making an R implementation of the KR normalization code. 

I found it can take a long time to run for large matrices. It seems a bottleneck is line 88 at https://github.com/dozmorovlab/HiCcompare/blob/master/R/KRnormalization.R#L88. 

If x is the KR normalization vector, it's unnecessary to form the dense matrix diag(x). Surely there are more efficient solutions, eg using sweep.

**Comment by mdozmorov** [comment]
Thanks, @jnasser3. We are not sure how to address your concern. Would you mind to suggest some code solution? Or, better yet, make a pull request? Thanks!

**Comment by mdozmorov** [comment]
Closing this issue due to lack of suggestions.
