### ISSUE TITLE
loess normalization error

### ISSUE THREAD

**Issue by BenxiaHu** [dozmorovlab/HiCcompare#22]
hello, when I ran HiCcompare to analyze two 40kb contact matrices, I got this error:
> hic.list <- hic_loess(hic.list, parallel = TRUE)
Span for loess: 0.0553159751353865
GCV for loess: 2.1838746854347e-06
AIC for loess: 1.27145513597705
Span for loess: 0.145845268859101
GCV for loess: 5.54106850960171e-06
AIC for loess: 1.2204086523086
Span for loess: 0.0853351658453019
GCV for loess: 4.96298216938726e-06
AIC for loess: 1.31897101094325
Error in result[[njob]] <- value : 
  attempt to select less than one element in OneIndex
Calls: hic_loess ... <Anonymous> -> <Anonymous> -> bploop -> bploop.lapply

do you know how to deal with this issue?
Best,

**Comment by mdozmorov** [comment]
Data sparsity is likely the cause. Can you try 100Kb data?

**Comment by BenxiaHu** [comment]
I can successfully run HiCcompare on 10kb matrix. but it can not analyze 40kb matrix.

**Comment by mdozmorov** [comment]
Then, I'd go with 10kb results. To debug 40kb data, I need a minimal example, code with a subset of data (save as Rds). 
Another thought - do you use parallelization? If yes, disable and try again.

**Comment by BenxiaHu** [comment]
_do you use parallelization? If yes, disable and try again._

yes, I set parallel to True. I am trying to disable parallel and run HiCcompare again.
Thanks

**Comment by BenxiaHu** [comment]
it works. thanks a lot.

Now I have another question: does HiCcompare perform quantile normalization for 2 different Hi-C with different sequencing depth？

**Comment by mdozmorov** [comment]
Yes, HiCcompare accounts for depth differences. You don't need to worry about it, but if you do, see the [Total Sum Scaling](https://www.bioconductor.org/packages/release/bioc/vignettes/HiCcompare/inst/doc/HiCcompare-vignette.html#total-sum-scaling) section.

**Comment by biohubx** [comment]
thanks.
based on this section: If you are performing your HiCcompare analysis on the entire genome you can perform total sum scaling on the data before performing loess normalization. This requires the use of a list of hic.table objects, one for each chromosome. Additionally, when you create these hic.table objects you must set `**scale = FALSE**`. Once you have your list of hic.table objects you can then perform total sum scaling.

I used this command to create hic.table objects for the entire genome:
# for all chromosomes
hic.list <- mapply(create.hic.table, dat1, dat2, SIMPLIFY = FALSE,**scale=FALSE**)

I found that the IF2 was still scaled: `**IF2_scaled = IF2 / (sum(IF2)/sum(IF1)).**`
![image](https://user-images.githubusercontent.com/12387462/100410104-a8e95600-303b-11eb-84da-551512b8ad6b.png)

do you know how to set scale=FALSE when running hic.list <- mapply(create.hic.table, dat1, dat2, SIMPLIFY = FALSE,**scale=FALSE**)?

Best,

**Comment by BenxiaHu** [comment]
thanks

**Comment by mdozmorov** [comment]
The purpose of Loess normalization is to adjust (rescale) the data so the differences between two Hi-C datasets are minimized. So, you always will see rescaled data after normalization. Unless you have wildly different sequencing depth, I won't worry about rescaling and let Loess do its job.

**Comment by mdozmorov** [comment]
Closed, please, ask in this thread if any other questions.
