### ISSUE TITLE
Why are the results from method KRnorm different from results from Juicertools

### ISSUE THREAD

**Issue by junmeiW** [dozmorovlab/HiCcompare#23]
Hi,
  I've use the method `KRnorm `and `SCN `to normalization. I found that results from these 2 methods are all less than 1, and the `KRnorm` results are totally different from that from `Juicertools`
For example, results from `KRnorm`
region1 | region2 | IF
-- | -- | --
3000000 | 3000000 | 0.315465
3000000 | 3100000 | 0.081327
3100000 | 3100000 | 0.317527
3000000 | 3200000 | 0.042387

and `Juicertools`
region1 | region2 | IF
-- | -- | --
3000000| 3000000| 1816.6257
3000000| 3100000| 468.3274
3100000| 3100000| 1828.491
3000000| 3200000| 244.09053

Are these results reasonable? 

Looking forward to your reply!

**Comment by mdozmorov** [comment]
It is possible there is a bug in our implementation of [KRnormalization.R](https://github.com/dozmorovlab/HiCcompare/blob/master/R/KRnormalization.R). The KR normalization supposed to make rows and columns sum to one. Try to find Juicer's code and compare it with our implementation, or, better yet, with the original [KR paper](https://core.ac.uk/download/pdf/62912562.pdf).

**Comment by junmeiW** [comment]
Thanks to your suggestion, I'll check that.
