### ISSUE TITLE
Issue installing HiCcompare

### ISSUE THREAD

**Issue by hannahdevens** [dozmorovlab/HiCcompare#26]
Hi, I am interested in using HiCcompare for a project I am working on, but I am having difficulty installing it in R using either of the 2 methods suggested on GitHub. When I try installing via BiocManager, I get the following error: 
Error: package or namespace load failed for ‘HiCcompare’ in dyn.load(file, DLLpath = DLLpath, ...): unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so': dlopen(/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so, 0x0006): Symbol not found: (__gfortran_os_error_at) Referenced from: '/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DNAcopy/libs/DNAcopy.so' Expected in: '/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libgfortran.5.dylib’

When I try installing via GitHub, I get this error:
   ERROR: package installation failed
Error: Failed to install 'HiCcompare' from GitHub:
 ! System command 'R’ failed

Do you have any ideas about what is going wrong? I am using R 4.2.

**Comment by mdozmorov** [comment]
Update 2022-11-28:
```r
devtools::install_github("dozmorovlab/HiCcompare")
```
will install the package. The function `get_CNV()` has been disabled, as well as the `QDNAseq` package that depends on `DNAcopy` and `gfortran`. This function won't affect functionality, it is an auxiliary function to detect CNVs from BAM files.

Updating Bioconductor will take more work. But as of now, HiCcompare is installable.

**Comment by hannahdevens** [comment]
Thanks so much!
