### ISSUE TITLE
How to select A.min values using filter_param function?

### ISSUE THREAD

**Issue by ashishjain1988** [dozmorovlab/HiCcompare#29]
Hi,

We have only one HiC sample per condition and we are trying to find out differential contacts. While using the default filtering we saw a large number of differential contacts that includes a lot of noise. We tried using the filter_params function to select the A.min values for filtering. I am not sure how to select the A.min value based on the plot from filter_params function as it seems pretty different from the one in the example data. Here is the plot that I got for chromosome 4.
![image](https://user-images.githubusercontent.com/9519687/236248490-2b59a3a0-e3a7-4671-9b8f-7e60ba021b17.png)

However, the plot for chromosome 22 something like this:
![image](https://user-images.githubusercontent.com/9519687/236248407-9e04f1b7-f081-4a06-8fbb-01c9bb04fe24.png)

We are interested in the analyzing differential contacts in chromosome 4 for our project.

Thanks,
Ashish Jain

**Comment by mdozmorov** [comment]
The plot for chromosome 4 tells that A = 10 will give a reasonable balance of true and false positive rates. I'm not sure what's going on with chromosome 22 - it may have insufficient contacts due to sparsity and being the smallest chromosome. Please, check the actual data, visualize the chr22 matrix. In general, HiCcompare is relatively robust to the choices of A.

**Comment by ashishjain1988** [comment]
Hi @mdozmorov, I have another question regarding the filtering process. It is fine if we remove the self ligated contacts from the data before the loess normalization or after carrying out the differential contact analysis?

**Comment by mdozmorov** [comment]
Any pipeline for Hi-C processing should already filter self-ligated and other artifacts. Not sure why the data you are referring to that has it.

**Comment by ashishjain1988** [comment]
Actually, I am using the data generated using Micro-C library preparation. Most of the HiC data processing pipelines takes input the restriction enzyme digested HiC data. I tried to use them for normalization or for fold-change calculation but I didn't find any filtering function for Micro-C data.
