### ISSUE TITLE
  could not find function "hic_compare"

### ISSUE THREAD

**Issue by RuiqinZheng** [dozmorovlab/HiCcompare#3]
Hi, I got some error messages when use the software, How can I solve this? maybe the reason is that I didn't install the package compelely?
> hic.table = hic_compare(hic.table, Plot = TRUE)
Error in hic_compare(hic.table, Plot = TRUE) : 
  could not find function "hic_compare"

Best wishes!

**Comment by RuiqinZheng** [comment]
I hava solved the problem !
Thanks!
But I hava another question:
When the package compute the different interaction,Whether the  effects of  different sequencing depth were removed?

**Comment by jstansfield0** [comment]
Assuming you normalized your data with hic_loess() then yes the effects of sequencing depth should be removed.
