### ISSUE TITLE
Warnings from simpleLoess, effect on results?

### ISSUE THREAD

**Issue by TeiturAK** [dozmorovlab/HiCcompare#30]
Hi,

Thank you for a great tool.

I am getting these warnings when I run hic_loess:
```
There were 11 warnings (use warnings() to see them)
1: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  ... : pseudoinverse used at 2
2: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  ... : neighborhood radius 1
3: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  ... : reciprocal condition number  0
...
```
From your manual (https://www.bioconductor.org/packages/release/bioc/manuals/HiCcompare/man/HiCcompare.pdf):
Note: if you receive the warning "In simpleLoess(y, x, w, span, degree = degree, parametric
= parametric, ... :pseudoinverse used..." it should not effect your results, however it can be avoided
by manually setting the span to a larger value using the span option.

Are the errors mentioning neighborhood radius and reciprocal condition number related to the pseudoinverse and can be assumed to have little effect on the result?

**Comment by TeiturAK** [comment]
Setting span = 0.05 in hic_loess removes this warning, as described in this thread: https://github.com/dozmorovlab/HiCcompare/issues/16#:~:text=%22make%20span%20bigger,at%20vcu%20.%20edu

**Comment by mdozmorov** [comment]
Great, that's the correct solution. The issue arises if the data is sparse and having a fixed larger span adds stability to the loess procedure.
