### ISSUE TITLE
Advice on value for A

### ISSUE THREAD

**Issue by TeiturAK** [dozmorovlab/HiCcompare#31]
Hi,

could you please advice on the selection of A from the filter_params plots? It looks quite different fromt the examples I've seen. I also attached the MD (all chromosomes) after selecting A = NA which was then automatically set to 7. Is the assymmetry from low to high abundance regions something can be expected between samples coming from two completely different tissue types? 

![image](https://github.com/dozmorovlab/HiCcompare/assets/46961584/a53e03b0-99cf-442d-8e8f-9f0b44a48a17)

![image](https://github.com/dozmorovlab/HiCcompare/assets/46961584/14d4ab2d-cf96-4ec7-94dd-5d3b14693883)

**Comment by TeiturAK** [comment]
Updated question with more information

**Comment by mdozmorov** [comment]
Hi @TeiturAK, you may set A=10 if you want to minimize false positives. That's the minimum average expression (A) where False positives rate drops and True positives rate increases. The automatic selection of A=7 is also appropriate. 

Your MD plot also looks good. The data appears to be deeply sequenced, balanced. The disbalance of up- and downregulated interactions at shorter distances is expected for different tissue types. I suggest focusing on the distance range up to ~100, interactions gained in one cell type appear the main driver of differences.

**Comment by TeiturAK** [comment]
Thank you very much for the help and feedback. Closing this.
