### ISSUE TITLE
the data is mismatch?

### ISSUE THREAD

**Issue by RuiqinZheng** [dozmorovlab/HiCcompare#5]
> head(HMEC.chr22)
   region1  region2   IF
1 16000000 16000000    5
2 16000000 16500000    2
3 16500000 16500000  297
4 16000000 17000000    5
5 16500000 17000000   92
6 17000000 17000000 5690

> head(NHEK.chr22)
   region1  region2    IF
1 16000000 16000000     6
2 16000000 16500000    10
3 16500000 16500000   554
4 16000000 17000000    17
5 16500000 17000000   320
6 17000000 17000000 10880
> head(chr22.table)
    chr1   start1     end1  chr2   start2     end2  IF1         IF2 D
1: chr22 16000000 16500000 chr22 16000000 16500000    5    5.203323 0
2: chr22 16000000 16500000 chr22 16500000 17000000    2    8.672206 1
3: chr22 16500000 17000000 chr22 16500000 17000000  297  480.440193 0
4: chr22 16000000 16500000 chr22 17000000 17500000    5   14.742750 2
5: chr22 16500000 17000000 chr22 17000000 17500000   92  277.510581 1
6: chr22 17000000 17500000 chr22 17000000 17500000 5690 9435.359752 0
            M
1: 0.05750528
2: 2.11639897
3: 0.69389392
4: 1.56000562
5: 1.59283701
6: 0.72964887

you see ,1) the original IF2 should be 6,but why the IF2 is 5.203323 in hic.table?
2) in my own data 
the first row of first data is:
1	1	624.0
the first row of second data is:
1	1	821.0
but why in the hic.table like this?
   chr1 start1 end1 chr2 start2 end2  IF1       IF2 D            M   
1: chr1      1    2 chr1      1    2  **624  572.9156 0** -0.123223336 
Does the software have do something when I use create.hic.table?
another question is  can I use this package to caculate inter-chromosme different interacion?
Best Wishes~
Thanks a lot!

**Comment by jstansfield0** [comment]
The data is not a mismatch. Scaling is performed by default in create.hic.table. You can turn it off if you set scale = FALSE. 

HiCcompare is not designed for looking at inter-chromosomal differences. Most inter-chromosomal contact maps are very sparse and noisy which make them hard to analyze.

**Comment by RuiqinZheng** [comment]
oh,I see it also can caculate the difference bwteen different-chromsome right? but the results maybe not crediable?

**Comment by jstansfield0** [comment]
I think you will get errors if you try to use inter-chromosomal data due to the fact that distance cannot be calculated between different chromosomes.

**Comment by RuiqinZheng** [comment]
yeah you are right.but if I just consider the all chromosome interactions as a big chromsome interaction?
and if I set the scale=FALSE,does it will influence the final result?

**Comment by jstansfield0** [comment]
I would not recommend combining all the data into a single matrix. It most likely will not work as this is not the intended use of HiCcompare. 

Setting scale = FALSE just changes if there is an initial scaling based on total number of reads. The loess normalization should be able to account for total number of reads as well and scaling is not always necessary.

**Comment by RuiqinZheng** [comment]
OK! Thanks a lot !
